import { MdGroups } from "react-icons/md";

const iconColor = '#4ec1fc';

export const reflectionInfo = {
  Le_Trinh_Quoc_Huynh: {
    text: [
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
    ],
    image: <img src='QuocHuynh.jpeg' alt='Le_Trinh_Quoc_Huynh' />,
  },
  Dang_Thai_Hoang: {
    text: [
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      [
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
      ],
    ],
    image: <img src="ThaiHoang.jpeg" alt='Dang_Thai_Hoang' />,
  },
  Vu_Tuan_Linh: {
    text: [
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
    ],
    image: <img src='TuanLinh.png' alt='Vu_Tuan_Linh' />,
  },
  Dau_Hoang_Minh: {
    text: [
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      [
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
      ],
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
    ],
    image: <img src='HoangMinh.jpeg' alt='Dau_Hoang_Minh' />,
  },
  The_whole_group: {
    text: [
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
      [
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
        "Eos takimata vero accusam est amet no. Sit stet amet et et at. Duo et sit at ea et nonumy..",
      ],
      "Elitr sadipscing nonumy et sit et, duo sanctus kasd et sea no justo ipsum sit. Accusam ipsum sadipscing voluptua accusam et dolor stet dolores stet, ut amet diam amet magna at stet no dolore. No ipsum sanctus rebum gubergren eirmod invidunt. No erat et lorem eos kasd. Gubergren no est consetetur sea. Sea et kasd sed dolor stet, diam et at sed diam ea eos, erat clita est erat est vero duo, sit erat et sadipscing duo. Diam est sea ea amet dolore magna diam ut sadipscing. Dolore sit sed sanctus et, justo eos dolores gubergren no invidunt gubergren elitr. Erat amet duo sit dolore et, takimata tempor dolore est sea, lorem et lorem duo et est sadipscing sea. Labore aliquyam gubergren dolore labore eos voluptua dolor kasd. Elitr at invidunt et labore voluptua. Ut accusam diam vero nonumy amet dolores. Est no gubergren takimata nonumy ipsum ut amet et, at ipsum sed dolor amet gubergren sed, sed lorem rebum no ipsum eos ut erat. Et vero vero ut clita est kasd voluptua, tempor diam aliquyam eos dolore amet voluptua justo. Amet clita sanctus sit ea, dolor consetetur lorem takimata sit, at kasd dolor eos accusam kasd consetetur accusam ea,.",
    ],
    image: <MdGroups size={70} color={iconColor} />
  },
};
