export const projectOverview = {
  Topic: [
    `With busy urban lifestyles, more and more people find hearing natural and comfortable sounds a great way to relax, relieve stress, and increase productivity. It can be the sound of wind blowing from high on top of mountains, the hum of insects and animals deep into the jungle, and also somewhere we are more familiar, like inside the coffee shop where we hear people chatting along with the melodies of the songs. That idea, combined with our love of coding and technologies, has inspired us to build a small website where people can enjoy some unique sounds of different places. Moreover, users can also adjust relative sound levels to achieve perfectly balanced background noise. We call it "Mix in Sounds" or "MinS".`,
    `We aim to start MinS with a website platform and then transition to a mobile application that can run on both IOS and Android devices. RMIT students will be the first to utilize MinS before it is made available to other Internet users. If this project is successfully deployed, people will have a nice place to relax and enjoy high-quality melodies even if they are in bustling areas of the city. In addition, people can also use MinS while studying to improve concentration and efficiency or while sleeping to have a good relaxation. In the future, we will frequently upgrade MinS with more locations and soundtracks, as well as fix and modify the website according to users' feedback at the same time.`
  ],
  Motivation: [
    `In recent years, the occurrence of Covid-19 has brought to our lives many changes, and most of them are tremendously awful. To reduce the negative impact of this deadly virus, people are encouraged to apply social distancing methods, including limiting travel, staying home, and avoiding crowded areas. As a result, many people have to cancel their vacations and stay at home all day long. These experiences are, sometimes, quite dull and exhausting. We believe that listening to music or some natural melodies is one of the best ways for people to relax and to have a feeling of traveling elsewhere.`,
    "According to soundofsleep.com [1], background sounds that usually contain white noise have been shown to have promising results in improving behaviors and productivity. To be specific, it helps us enhance memories, deepens our meditation, sleeps quality as well as enhances concentration. MinS was developed to bring people a better quality of life with its pristine soundtracks and beautiful photographs. Moreover, this website also provides Pomodoro – a study tracking tool that people can use while studying and Spotify integrations to enjoy their own playlist of songs.",
    "In a highly competitive IT market, it is crucial that our team focus on web development trends. One of them is Accelerated Mobile Pages (AMP), which helps speed up web performance and reduce the risk of leaving by a user. The website will be optimized with a simplified and convenient design with basic features so every user can easily access it [2].",
    "To show to the future employer our ability to work on this project, the Spotifour team had made a clear plan with detailed descriptions, assigned different roles to team members, and built a specific timeline to work on this project, which will be discussed in the “Detailed description” section."
  ],
  Landscape: [
    "YouTube is one of the first to offer background noises videos, especially the sounds of nature like the rain, the wind, and the animals. However, users can only use a default set of sounds, and the quality, sometimes, cannot satisfy users' desires. My Noise is one of the most popular background sound platforms with high-quality soundtracks [3]. However, it does not have a good interface design, and some parts are confusing. MinS differs from other background noises generators by its free high-quality audio and the vast number of sounds provided. In addition, the website has a user-friendly design and offers lots of trending features so clients can have the best experience while using it. Users can access the website right on their phones, tablets, or laptops, and it will be available on famous browsers like Safari, Google Chrome, Firefox, and Microsoft Edge. ",
  ],
};

export const projectDetail = {
  Aims: [
    "The project aims to bring people a habit of using MinS. Whenever people feel tired, stressed out, they can play some gentle and undisturbed soundtracks to relax, relieve stress, and have a nice sleep. If people find it hard to concentrate while there are some annoying sounds from the surrounding environment, they can put their headphones on, open MinS, and listen to some enjoyable sounds of the workplaces. Or if people find it boring to stay home all day long, they can listen to beautiful melodies of nature to have the feeling of traveling somewhere. The reason for our target is that habit-forming can create unprompted engagement; people use our product on a daily routine without relying on advertisements, promotions, and other external triggers. As a result, such products usually have greater pricing flexibility, higher customer lifetime value, and supercharged growth compared to other competitors. We have four main goals to achieve the desired aim:",
    [
      "Our project's first goal is to design an excellent website interface, including choosing good color themes, typography, background pictures and defining the suitable layout and design of different components like the control bar, the header, buttons, etc. A well-designed website will bring a good first impression to customers and will likely extend the use time since customers find it easier to navigate around the website.",
      "Audio is one of the essential parts of the project because our website mainly focuses on background sounds. As a result, our second goal is to have a high-quality collection of soundtracks. We started with four main locations, which are by the beach, in the forest, in a café, and at the office; and in the future, our goal is to provide more places so users can have a variety of choices.",
      "After the website is developed, our next goal is to enhance the quality of the web, which includes eliminating any bugs in our system by doing a set of rigorous tests. In addition, our team can hear from customers' feedback to understand their needs and make improvements to the website.",
      `Our last goal is to approach a broad range of customers. We first begin with students in our department (around 100 users), then to RMIT students (around 1000 users), later to citizens around our region (around 10,000 users), and last is to people from all walks of life (more than 100,000 users). To achieve the goal, our team need to answer different questions like "what type of people are most likely to use the web?"," what is customers' need, and how can we provide it to them?", "What are current market trends and how to keep up-to-date?". From that, we can build a good marketing strategy and approach potential customers.`
    ],
  ],
  Plans_and_Progress: [
    "Overview",
    'In assignment 1 of Introduction to Information Technology, every student had a chance to talk about their desired project, and lots of interesting innovations were given. Hoang’s idea was to develop MinS – a background noise platform and it was chosen to be the Spotifour team’s first-ever project since it can be extremely helpful for students like us. It will be a place for people to relax, increasing productivity as well as deepening meditation.',
    'In general, MinS is a simple and easy-to-use website. When we first open up, the whole screen will be covered in black, and the logo will slowly appear. After that, it will display, under the logo, “Welcome to Mix in Sounds”, followed by a short description of the web. Users will then be asked to choose between four locations - Chilling by the Sea, Exploring the Forest, Relaxing in a Coffee Shop, and Working at the Office. After choosing the desired location, the website will relocate users to a new page, and more soundtracks of that place will be provided. The key point is that users can adjust the level of different sounds until their desired one was reached.',
    'PLANS',
    'STAGE 1:  Preparing & Researching',
    [
      'Preparing audio: Having a high-resolution audio collection is one of the most crucial parts of our project. We planned to invest in the H4n Pro Track – a specially designed microphone for ambiance sounds recording [4]. Hoang and Huynh will be responsible for going to and recording the sounds of different places. We will begin with the coffee shop, and the office since those areas can be easily accessed. For other locations (by the sea and in the forest), our team can wait for special occasions so there will be enough time for us to go, or if any team members have chances to go there, they will also take the work.',
      'Researching: To make sure everything is on the right path, Minh and Huynh have the responsibilities to do research and find down what are the requirements, what are the expectation from customers, and many more.'
    ],
    'STAGE 2: Designing',
    'When customers come to our website for the first time, a well-designed interface will give them an excellent first impression and impact how audiences perceive our brand. Hoang – who works in the UI&UX position – was responsible for delivering the website interface. Pinterest can be a good place for him to find some exciting designs, and Canva, in the meantime, will be used to design different components of the web. He will start by building the home page where users can navigate around and then to other locations like the seaside or forest. For each page, he first needs to find a suitable background picture, then builds a default header and a footer before developing the body part.',
    'STAGE 3: Developing the website',
    `The next part is to start developing the website based on the design. Since Linh has significant experience building complex websites, he will be the lead developer for this project. First, we will build the backend server for the website for storing all the audio files and ensure it can handle a small number of requests simultaneously. Next, our plan is to continue working on the front end of the website. We will focus on the website's functionality first, making sure it can get all the data from the backend, play and mix the sounds, and be able to work with Spotify without any issues. After that, we will then focus on styling the website to provide users with a nice-looking interface. The website must satisfy all those requirements before we deploy and introduce it to the world.`,
    'STAGE 4: Going live and Marketing',
    `This is the most exciting stage in our plan - introducing the website to the customers. For our project to go viral, marketing is the essential part that we need to concentrate on. We will focus on social media marketing since it is the easiest way to promote the website to a large number of people without any cost. First, we will promote it on different Facebook, Instagram, and TikTok pages that related to RMIT students and then expand to other universities in our country. Throughout this whole time, we will constantly be getting feedback from users to modify the website to fit their desire. Moreover, we always have to ensure that we upgrade the server to handle more and more users' requests.`,
    'STAGE 5: Expanding and Mobile app development',
    'If we have more resources, maybe from funds from investors, we will continue our strategy to develop and advertise our website to other customer groups. At this stage, we also plan to delegate our work by hiring new employers. Finally, if the website hits a large number of users, we will start to consider developing a mobile app with additional functionalities for users.',
    'PROGRESS',
    'So far, we have finished the researching and designing parts of the project:',
    'Research: To ensure that our project development is on the right path, the Spotifour team needs to do research as well as gather information to answer different questions, some of them are:',
    'What is the purpose of the MinS? - MinS provides high-quality background noises of different places.',
    'Who is our target audience? - Our project will be suitable for people of all ages, however, students and working people will be our main target.',
    `Why do users need our website? - Background noises which usually contain white noise have promising effects on improving people's moods, better sleep quality, and deepening concentration.`,
    'What will customers expect from a sound hosting website? - High-resolution and diverse sounds are the key points that users usually expect from a sound hosting platform.',
    `What are the main features that we would like to use? - The project's main feature is the ability to modify the volume of different sounds of a specific place.`,
    'What are additional features that customers would like to have? - Our website also provides a Spotify player for music lovers and Pomodoro for people who are working or studying.',
    'How to make a profit? - We intended to make a profit based on ads and provide a Member account.',
    'How to maintain customers’ engagement?',
    [
      'To maintain customer engagement, our team need to make frequent update to the website based on users’ feedback',
      'Sometimes, we can, randomly, give frequent users access to a special set of sounds, or new locations which are only offered in the Member package.'
    ],
    'Designing',
    'There is no set color theme for the website since every location has its own unique colors. However, most of the background pictures will be in low contrast so it can reduce causing eyestrain. In addition, since we aimed to build a simple and easy-to-use website, the layout and design of different components would not be too complicated.',
    'We started by building the home page, where users first access when they use the website. On top of the interface will locate some forewords of the web, and underneath are four locations that users can choose to go to.',
    'After selecting the desired location, users will then be relocated to a new page where more soundtracks of that place will be provided.',
    'The header, where the website logo and different locations are located, will lie on top of the window, and users can navigate to other places by clicking on them. The set of sounds will be on the right side of the screen. There will be a control bar for each sound for users to adjust. They can choose the sounds they desire by clicking on the play button and dragging the circle dot to the right for higher volume and the other for lowering. The play button will then be changed into the pause symbol in case users want to stop the sound.',
    'Underneath the sounds control panel, there are four circles with an icon inside, representing the weather mentioned before. Users can hold their mouse on that button, drag it up or down to adjust the volume.',
    'For music lovers, the Spotify player is located on the left side of the window and has some default music chosen by the host. If the users have a premium Spotify account, they can also log in and enjoy the entire length of the songs instead of the 30s each. The sound adjusting bar and playback & skip button are also provided for the users for better adjustment.',
    'Pomodoro is one of the trending education tools to help us keep track of our studies time and work effectively. It will be included on the website and displayed on top of the Spotify player. The default option is 25 minutes of working time, followed by 5 minutes of break. Users could also adjust the desired time by clicking on the “EDIT” button. After that, the interface of the Pomodoro will change, and there will be two arrows up-down for us to choose the desired working time.',
    `If the users are satisfied with the website, they can also support us by clicking on the “Support us” button on the bottom left of the interface. They will then be taken to a page where users can find more information about the creators and send a small donation. On the right side of the donation box is some extra information about the website, including the creators, the releasing date, and our slogan.`
  ],
  Roles: [
    "In this project, all team members participated in committing codes into the GitHub website and writing sections of the report. However, we could still distinguish the role of each member based on their responsibilities:",
    "Supervisor: Dau Hoang Minh",
    "As Minh was very disciplined, he was in charge of managing the working process as well as compiling all team members' work into a report that met the assignment's requirements. He divided the work into small tasks and then used the Asana application to assign them for each team member based on their strength. He also set the deadline to complete each task and arranged them appropriately based on the priority order and real working situation. At the final stage of the project, he completed the report by adding a cover page, table of content, references, and checking the Turnitin before submitting the final version to the teacher.",
    "Lead developer: Vu Tuan Linh",
    "As Linh was the only person in our team having experience making complex websites before, he was primarily responsible for developing our websites. Before doing the project, he assessed the complexity of our project idea and then explained to all members how to develop specific features for the website in general. During the project, Linh skillfully developed our website using HTML, CSS, and JavaScript programming languages, ensuring that it had all of the necessary features and could accommodate all of the information in our report. Also, he managed the project's source code using the GitHub repository, checked several commits from other members to ensure that there were no programming errors.",
    "UI/UX Designer: Dang Thai Hoang",
    "As Hoang was quite creative and good at designing, he acted as the designer of our project, who was in charge of both user interface and user experiences. He modified the website's color, font sizes, and pictures. Hoang worked closely with Tuan Linh to develop a user-friendly website: the website's layout was designed to make users feel relaxed, and the buttons were placed in convenient locations for clicking. He also sketched the project demo with images representing each website feature. Those illustrations were put into the presentation slides so that other people could understand our project more clearly.",
    "Researcher: Le Trinh Quoc Huynh",
    "As Huynh possesses excellent research and analytic skills, he was responsible for collecting information, audio sources, and any relevant documentation for our project. He did research to find a suitable audio source providing high-quality natural sounds for our website. In addition, Huynh was also in charge of making the Powerpoint slide which will be used to present our project idea to the teacher and all classmates. He conducted market research to determine our competitors in this field and the public's need for this service to create informative slides that would persuade all listeners."
  ],
  Scope_and_Limits: [
    "The feature that stands out most about our project is all the high-quality natural sounds we provide to users. This differentiates us from other websites and mobiles apps out there. Therefore, we should always prioritize our focus on building it. Other features, like Spotify integrations or Pomodoro, should only be considered after we have ensured the sound quality is good enough.",
    "In terms of coding work, we need to emphasize most on the back-end server. Minor frontend issues can be addressed later, but the server always has to work properly under high traffic, so our mobile app or website will not crash in such situations.",
    "When it comes to marketing, it is essential to target only a specific niche group of users. We will advertise ourselves to young people from 20-35 years old first since this group is more likely to feel stressed at work and often enjoy listening to something to stay focused. Only after that will we slowly shift our attention to other groups of users.",
  ],
  Tools_and_Technologies: [
    "The main technology for building this project is ReactJS [5]. It is utilized for building front-end components, including the sounds control panel, header, Pomodoro section, etc. Having worked as a web developer for over one year, only Linh has lots of experience with ReactJS, his role is to gather other team members’ code and manage the code’s repository.",
    "HTML and CSS will also be used for structuring and styling the project. All of the team members are familiar with these technologies since we have done some online courses and tutorials before (W3School, freecodecamp, etc).",
    "In addition, Spotify API [6] will be integrated into the website for playing songs and providing users' logins feature. Using API is still something new to our team and we have to do research about applying it into our code.",
    "With the help of Canva [7], we can build a demo interface of the website and different components. Hoang who was responsible for the UI-UX position had done several projects with Canva before because of its convenience and promptitude.",
    "For the soundtracks, if possible, we would like to invest in the Zoom H4n Pro - an exceptional microphone/digital audio recording device [8]. It is an easy-to-use technology and works best for ambiance recording. In addition, we also need an earphone to check the quality of the sound while it is being recorded.",
    "To have high resolution and nice-exposure pictures, we can use images from Unsplash [9] – a photo discovery platform for free to use, high-definition photos.",
    "While Firebase [10] will be used to store the database, different sound packages, and high-quality pictures, Git and Github help us with handling version controls and remote repositories. Spotifour members are familiar with these technologies since we had used them before in other projects, like assignment 2, or in other courses.",
    "All of the software that we use in this project is free of charge, our team can use them for commercial purposes and no licenses are needed."
  ],
  Testting: [
    "The final project must satisfy these four requirements:",
    [
      "The sound must be clear and high quality when users use the website or mobile app; users can also choose to play multiple sounds at the same time.",
      "Users can hear multiple sounds at the same time without any issues.",
      "The user interface of the app/website must be pleasant to users and responsive for all devices (phones, tablets, and desktops).",
      "The website and app must be any to handle a high number of users at the same time without significantly slowing down or crashing."
    ],
    "Therefore, our tests will be used to ensure all these four criteria will be met. We will use social media platforms like Facebook and Instagram to introduce our project and invite about 50 users to a meeting to try our software. In the meeting, we will let the volunteers try using the website and mobile app with different popular devices and mix the sounds together. Any problems or feedback with the sound quality, the front-end, and the performance of the site/app will be noted for future modification. After the meeting, we will try to make some adjustments according to the report and be ready to invite people to another meeting, maybe with a larger number of attendances being about 100 and 200. After a few rounds of testing like that, we believe it will be sufficient for us to officially launch the website or mobile app."
  ],
  Timeframe: [
    "Table link: https://docs.google.com/document/d/1Sw1u1eMhimXa_tLBrdAC85PDBwQOiJCTjJxi1fW-9f8/edit"
  ],
  Risks: [
    "Based on the characteristics of our project idea, there are three main risks we can identify at the moment:",
    [
      "The sound quality: The sound quality provided to the users is the key-centric component of our project. However, most of us do not have much experience working with websites and apps that integrate with audio files. We have to do a lot of research and learn many new technologies, both hardware and software, to gain enough knowledge to do this project. For example, we have to find ways to provide users with great sounds for different devices run by different operating systems.",
      "The performance of our website/app: The audio files loading from the server to the frontend website or mobile app can be considered quite heavy and require significant optimization work. In a bad scenario, the website or app interface will be crashed or have slow interaction, making a bad user experience.",
      "Too many users using the website or our mobile app simultaneously can negatively impact our backend server since it has to manage a massive amount of requests. We always have to ensure the backend is strong enough for such cases."
    ]
  ],
  Group_processes_and_communications: [
    "We all recognized the importance of team communication, so we tried to communicate with each other as much as possible throughout the working process, using a variety of platforms.",
    `Aside from lectures and tutorials, we met face-to-face once a week on average at the "Student Hub" room in RMIT Hanoi Campus to discuss the group assignment process. During those meetings, we usually shared our opinion about the project idea: Which features should we include?, Which tools should we use?,  How can we improve the current draft? , …`,
    `On the other hand, there were times that we couldn't meet offline due to the Covid-19 pandemic or Christmas Holiday Week (the campus was closed). So we decided to meet online at those times using the "Google Meet" application, a video conferencing service from Google [11]. Online meetings were usually shorter than offline meetings, lasting about one hour, and we only discussed how to handle several specific tasks, such as Git and GitHub management.`,
    `In addition, we had a Driver folder for all members to upload their documents and check other people's work and a Messenger group chat for daily communication and discussion of minor project issues. Asana was a customizable workplace content management system that helped us manage a large amount of work and assign tasks to each team member [12]. Thanks to Asana, members working on their tasks would be notified if the deadline or content of the work changed.`
  ],
};
